# Generated by Django 5.2.8 on 2025-11-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_p', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('rut', models.IntegerField(null=True)),
                ('direccion_p', models.CharField(max_length=150)),
                ('email_p', models.CharField(max_length=100)),
                ('edad_p', models.IntegerField(null=True)),
            ],
        ),
    ]
